### PR TITLE
Add Sinatra example to docs

### PR DESCRIPTION
**Pull request by robinjmurphy**
Hello! Thanks for the great library. I've been building a GraphQL Sinatra example this weekend and have really enjoyed working with it.

I thought it might be useful for other people, so I've added a link to my example in the docs underneath your Rails one.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Hi! I'd love to include a link to a Sinatra example, thank you for sharing. 

This HTML file is actually the generated output of a Markdown file on the master brach: 

https://github.com/rmosolgo/graphql-ruby/blob/master/guides/related_projects.md

Could you update that file instead? Then I'll regenerate the HTML & push to github pages.

**Comment by robinjmurphy** [comment]
Thanks. I've updated the branch. Should be updating the Markdown in master now.

**Comment by rmosolgo** [comment]
Thanks!

**Comment by rmosolgo** [comment]
generated and pushed! http://rmosolgo.github.io/graphql-ruby/related_projects

**Pull request merged**
