### PR TITLE
issue #224

### PR DESCRIPTION
**Pull request by b8in**

### CODE REVIEW

**Comment by rmosolgo** [comment]
This is great, do you mind adding a test to be sure we maintain this in the future? For example, you might add one here: 

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/relay/mutation_spec.rb

that asserts that the mutation field's description is present, eg 

```ruby 
it "applies the description to the derived field" do 
   assert_equal "Add a ship to this faction", IntroduceShipMutation.field.description
end 
```

**Comment by b8in** [comment]
Sure, with pleasure :)

**Comment by b8in** [comment]
I've just commited the test you mentioned above.
I didn't try to write any other checks - I think that one would be enough.

**Comment by rmosolgo** [comment]
awesome, thanks for this improvement!!

**Comment by rmosolgo** [comment]
:ship: in 0.18.7

**Comment by b8in** [comment]
Thanks, updated the gem on my side, everything's ok.

**Pull request merged**
