### PR TITLE
(WIP) Serilaize/deserialize GlobalID::Identification

### PR DESCRIPTION
**Pull request by cpunion**
Make SubscriptionType's field receive deserialized model object instead of Hash object.

See https://github.com/rmosolgo/graphql-ruby/issues/969

### CODE REVIEW

**Comment by cpunion** [comment]
After this commit, there is another problem yet (See below). We can solved by:

```ruby
# app/graphql/types/subscription_type.rb
Types::SubscriptionType = GraphQL::ObjectType.define do
  name "Subscription"
  field :postSent, !Types::PostType, "A post was published to the blog" do
    resolve ->(obj, args, ctx) {
      obj
    }
  end
end
```

But I think the default behavior (call post#postSent) in this context doesn't make sense.

```
There was an exception - NoMethodError(undefined method `postSent' for #<Post:0x007f8d68b48848>)
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activemodel-5.1.3/lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/field/resolve.rb:54:in `public_send'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/field/resolve.rb:54:in `call'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/subscriptions/instrumentation.rb:59:in `call'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/field.rb:230:in `resolve'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:253:in `call'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema/middleware_chain.rb:45:in `invoke_core'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:107:in `resolve_field'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:71:in `block (2 levels) in resolve_selection'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `block in trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:70:in `block in resolve_selection'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:63:in `each'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:63:in `resolve_selection'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `block in trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:95:in `begin_query'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:72:in `block in run_as_multiplex'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:71:in `map'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:71:in `run_as_multiplex'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:172:in `with_instrumentation'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `block in trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `trace'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:50:in `run_queries'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:40:in `run_all'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema.rb:284:in `block in multiplex'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema.rb:591:in `with_definition_error_check'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema.rb:283:in `multiplex'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/schema.rb:260:in `execute'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/subscriptions.rb:70:in `execute'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/graphql-1.7.3/lib/graphql/subscriptions/action_cable_subscriptions.rb:100:in `block (2 levels) in write_subscription'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/channel/streams.rb:155:in `block in stream_decoder'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker.rb:58:in `block in invoke'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker.rb:39:in `block in work'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `block in with_database_connections'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `block in tag'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `tag'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `with_database_connections'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/engine.rb:60:in `block (4 levels) in <class:Engine>'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/engine.rb:55:in `block (3 levels) in <class:Engine>'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker.rb:38:in `work'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker.rb:56:in `invoke'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/actioncable-5.1.3/lib/action_cable/server/worker.rb:51:in `block in async_invoke'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/lijie/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by rmosolgo** [comment]
Hi, thanks for checking out the serialization here! I agree that we'll need something more robust. I'll take a closer look tomorrow at the details.

**Comment by rmosolgo** [comment]
> the default behavior (call post#postSent) in this context doesn't make sense

I agree, the change you suggested sounds better to me. (In fact, I thought it already worked that way ... let me have a look at it!)

**Comment by rmosolgo** [comment]
Thanks again for pushing this improvement! I cherry-picked it and merged it as part of #1004. 

I also addressed the issue you mentioned about `resolve`, the  change was here: 

https://github.com/rmosolgo/graphql-ruby/pull/1004/files#diff-fb9aa2c62108d972109e1c846e76c7acL59

**Pull request closed without merging**
