### PR TITLE
Unauthorized field hook

### PR DESCRIPTION
**Pull request by noaelad**
Implementation for Issue #1964 - creating a hook for custom handling of an unauthorized field.

TODO:
- [X] Implement hook
- [X] Ensure existing tests pass
- [x] Extend tests to cover new hook
- [x] Add documentation for new hook
- [ ] ~~Bump version?~~

### CODE REVIEW

**Comment by noaelad** [comment]
@rmosolgo some pieces of this are still missing, but I would love to get your input on what I've done so far, and if you notice anything else needed that I haven't listed above.

**Comment by rmosolgo** [comment]
Hey! Sorry for the slow review. This is looking great! I don't have anything to add, except, don't worry about bumping the version. I'll take care of that when I'm ready to release to RubyGems.

**Comment by noaelad** [comment]
@rmosolgo this took a while with the holiday break, finally ready for review.

**Comment by noaelad** [comment]
Oh nice! I was just about to push the same exact fix but you beat me to it. Thanks for getting this in!

**Pull request merged**
