### PR TITLE
Allow autoloading of relay ids in input objects, move `GraphQL::Schema::Resolver::LoadApplicationObjectFailedError` to `GraphQL::LoadApplicationObjectFailedError`.

### PR DESCRIPTION
**Pull request by lemuelbarango**
Fix for this issue: https://github.com/rmosolgo/graphql-ruby/issues/1838

Initial idea was to make `GraphQL::Schema::InputObject` inherit from `GraphQL::Schema::Resolver`...

Decided to go for a simpler PR and move loads functionality from `GraphQL::Schema::Resolver` class to `GraphQL::Schema::Member::HasArguments` module. This allows the functionality to be reused in the `GraphQL::Schema::InputObject` class

**Open for feedback or different ideas.**

TODO

- [x] Add more specs to test `loads:` arguments on input object

### CODE REVIEW

**Comment by lemuelbarango** [comment]
I should note the `loads` argument in input objects works only in conjunction with  `MutationType`

For this to work with `QueryType` I think the `InputObject` resolve would have to be refactored

**Comment by chrisseto** [comment]
@lemuelbarango, how difficult do you think it would be to get `loads:` working with `QueryType`?

It would be extremely useful to have it work in both cases.

@rmosolgo, do you think the loading logic could be refactored onto/into the `Context` class?

**Comment by lemuelbarango** [comment]
@chrisseto added should work with `QueryTypes` now

**Comment by chrisseto** [comment]
@lemuelbarango 🎉 you da real MVP

**Comment by rmosolgo** [comment]
Thanks for your work here, I'll take a close look soon!

**Comment by rmosolgo** [comment]
Thanks again for taking this on, looks like it turned out really nice! I just made one change, moving the error class to the top-level `GraphQL::` namespace. This might be a breaking change for people who reference that error in their code, but the new namespace is simpler and we can be sure to make it stable from now on 💫

**Pull request merged**
