### PR TITLE
Remove partial `opentelemetry` implementation

### PR DESCRIPTION
**Pull request by ravangen**
Optional followup to https://github.com/rmosolgo/graphql-ruby/pull/4077 and a [comment](https://github.com/rmosolgo/graphql-ruby/pull/4077#issuecomment-1142365741) impacting `2.0.9` and `1.13.13`

This PR seeks to return this gem to a "stable state" and not have any misleading or inaccessible code. It is a revert of all the tracing changes with the exception of `lib/graphql/tracing/platform_tracing.rb`. I still believe there is some value in having a way to access the execution context when tracing, and this was the recommend way to achieve this per https://github.com/rmosolgo/graphql-ruby/issues/4001.

First-party OpenTelemetry instrumentation would be wonderful, but it was not my intention to force this decision either way as part of the original suggested changes.

Apologies again for the confusion and happy to try and help sort this out based on your recommendations.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Likewise, sorry I misunderstood the nature of these files in the original PR 🤦  I have no preference whether they're here or in opentelemetry-ruby. 

My only hangup, IIRC, the only test for passing `trace_phase` was the opentelemetry tracer itself. If we remove it here, then an over-enthusiastic refactor might remove that option, since it's not used anywhere in this repo.

Would you mind adding a note to the source (or a test, if you can think of a handy way to add one) to help me maintain compatibility in the future?

**Comment by rmosolgo** [comment]
Added a comment in f4d99f692

**Comment by ravangen** [comment]
I still will see about adding a test case soon, just to have that peace of mind. Been a bit distracted recently.

**Comment by toneymathews** [comment]
Can we pls add these changes to `1.13.x` as well? I see `1.13.14` still has the opentelemetry implementation.

**Comment by rmosolgo** [comment]
Oops -- just released this in 1.13.15, too!

**Pull request merged**
