### PR TITLE
`connection?` is not properly set when parsing the IDL

### PR DESCRIPTION
**Pull request by gjtorikian**
When using ` GraphQL::Schema.from_definition`, it seems that `connection?` is always `false`. I've added a failing test, but have yet to find a root cause.

### CODE REVIEW

**Comment by gjtorikian** [comment]
I'm having a _very_ hard time figuring out how to fix this. 😓

**Comment by rmosolgo** [comment]
Good catch! Here's where `GraphQL::Field`s are created when parsing the IDL: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/build_from_definition.rb#L275-L282

I think you could assign [`field.connection=`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/field.rb#L181) _after_  building it, eg: 

```ruby
field.connection = field_definition.type.ends_with?("Connection") # or is it `String#end_with?`, I always forget
```

In any case, I think that's the spot of code that needs a fix!

**Comment by gjtorikian** [comment]
Ok, based on that hint I think I got it.

**Comment by rmosolgo** [comment]
👏 Sweet! Good call on the non-null handling.

**Pull request merged**
