### PR TITLE
Add urql actioncable client

### PR DESCRIPTION
**Pull request by udl**
This PR resolves https://github.com/rmosolgo/graphql-ruby/issues/4872

Please let me know in case I should change something. Thanks!

### CODE REVIEW

**Comment by rmosolgo** [comment]
Hey, thanks for adding this! I'll take a close look soon.

**Comment by rmosolgo** [comment]
Thanks for adding this! I modified it a bit -- working into the existing `SubscriptionExchange` -- and added tests. I pushed to your branch, but for some reason, my commit didn't appear here, so I opened #4886 with our commits and merged that. 

It's now released in graphql-ruby-client 1.13.3 -- let me know if you run into any trouble with it!

**Comment by udl** [comment]
Perfect, thank you! Will try it in the coming days

**Comment by udl** [comment]
I've tried and it works just fine!

**Pull request closed without merging**
