### PR TITLE
Add support for Statsd tracing

### PR DESCRIPTION
**Pull request by esjee**
Usage:
```
MySchema = GraphQL::SChema.define do
  ...
  use GraphQL::Tracing::StatsdTracing, statsd: Statsd.new('localhost', 1337)
  ...
end
```

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: Looks good to me! As a bonus, do you have any dashboard screenshots you could add to the docs?

**Comment by esjee** [comment]
Getting screenshots is going to be tough, but I could test it with some faux statsd server.

**Comment by rmosolgo** [comment]
Is this still in progress?

**Comment by esjee** [comment]
Seems to be tackled in #1060 !

**Comment by esjee** [comment]
Sorry, I don't have any screenshots for you. We don't actually use statsd on production anymore, and getting it running on a local machine seems to be a lot of work :see_no_evil: 
Plus, it doesn't like there's _just one_ statds client to begin with. 

Best I can do is something like this: 

```
StatsD Metric: myapp.parse.graphql 0|ms|#environment
StatsD Metric: myapp.validate.graphql 2|ms|#environment
StatsD Metric: myapp.analyze.graphql 2|ms|#environment
StatsD Metric: myapp.analyze.graphql 6|ms|#environment
StatsD Metric: myapp.Query.reports 12|ms|#environment
StatsD Metric: myapp.Query.node 51|ms|#environment
StatsD Metric: myapp.execute.graphql 51|ms|#environment
StatsD Metric: myapp.PostConnection.edges 309|ms|#environment
StatsD Metric: myapp.Homepage_query 1|c|#environment
```

**Comment by rmosolgo** [comment]
> don't actually use statsd

😬  

Do we know anyone who wants this? If not, how about we close it until we know someone who wants to use it? We can always reopen when we need it!

**Comment by rmosolgo** [comment]
(sorry, didn't mean to preemptively close this!)

**Comment by esjee** [comment]
Sure, that works for me.

**Pull request closed without merging**
