### PR TITLE
Add GraphQL::Deprecation.warn

### LINKED ISSUE #3290: Allow usage of deprecated functionality to be treated as an error
**Is your feature request related to a problem? Please describe.**

There are lots of deprecation warnings for v2.0, and I'd like to catch those in CI and migrate off the functionality now.

We use `config.active_support.deprecation = :raise` in the development and test environments in our Rails application to do this for Rails itself.

**Describe the solution you'd like**

Use a custom method to warn about deprecation, and allow configuration to raise an error rather than just warning.

**Describe alternatives you've considered**

Rather than implementing this entirely from scratch, it would also solve our problem if graphql-ruby used `ActiveSupport::Deprecation.warn` if it is defined, and otherwise fell back to `Kernel#warn`.

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #3290

### CODE REVIEW

**Comment by mrcasals** [comment]
Hi @rmosolgo! After this PR I'm getting this error:

```
uninitialized constant GraphQL::Deprecation_ID_TYPE
```

It seems to be a problem with the find-and-replace, just like in commit 105de58. Unfortunately, this got into release 1.12.2, so a new release is required to fix this!

**Comment by rmosolgo** [comment]
Ick, thanks for reporting this. I think you're right. I'll take a look, @mrcasals.

**Comment by rmosolgo** [comment]
Fixed in 5133a157e and shipped in 1.12.3 -- let me know how that version works for you, @mrcasals !

**Comment by mrcasals** [comment]
Awesome, thanks for the quick response! ❤️

**Pull request merged**
