### PR TITLE
Pluggable action cable serializer

### PR DESCRIPTION
**Pull request by staugaard**
This allows us to use our own serializer for action cable subscriptions.

I can't find a good way to test this.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: This is great, I might even move it up to the parent class so I can use it _outside_ of ActionCable! 

Do you mind sharing, how is your custom serializer different from the included one?

**Comment by staugaard** [comment]
The project where I need this on builds ActiveModel objects from http responses, and I need to send those objects to subscriptions.

I'm currently using this serializer:

```ruby
module ActionCableModelSerializer
  def self.dump(model)
    JSON.dump(
      class: model.class.name,
      attributes: model.as_json
    )
  end

  def self.load(str)
    json = JSON.parse(str)
    model_class = Object.const_get(json.fetch('class'))
    model_class.new(json.fetch('attributes'))
  end
end

```

**Comment by staugaard** [comment]
any chance of getting this merged?

**Comment by rmosolgo** [comment]
Yes, I'll try to add a test today! I was just waiting to see what your customization was, in case there was another takeaway for the gem. But it sounds like not!

**Comment by rmosolgo** [comment]
Thanks for the improvement!

**Pull request merged**
