### PR TITLE
Hackaton new website graphQl-ruby WIP

### PR DESCRIPTION
**Pull request by thomasoldenburger**

### CODE REVIEW

**Comment by rmosolgo** [comment]
Awesome, thanks for pushing up your work on this design so far!

**Comment by emilebosch** [comment]
We'll fix this ASAP! And redo the code, ETA 2 weeks or so. 😬 Hope that is okay.

**Comment by Willianvdv** [comment]
@emilebosch let me know if you need help!

**Comment by emilebosch** [comment]
Actually you can! You can help build the SASS for the frontend! Ping me #ruby on graphql slack!

**Comment by Willianvdv** [comment]
This is the design made by @emilebosch and @thomasoldenburger https://projects.invisionapp.com/share/BDD7FGFH4#/screens

Pretty nice if you ask me!

**Comment by rmosolgo** [comment]
🙌 !!

**Comment by emilebosch** [comment]
Oh my, this is a month ago. I'll start hacking tomorrow.

**Comment by rmosolgo** [comment]
Feel free to reopen this if you get a chance to pick it up again :)

**Pull request closed without merging**
