### PR TITLE
Improve object generator

### LINKED ISSUE #2951: Scaffold Generator for DB schema
**Is your feature request related to a problem? Please describe.**

When I write RESTful endpoints, I can use `rails g scaffold <model>` or `rails g resource <model>` to automatically create fetchers/mutators for the resource. But when I write GraphQL endpoints, I have to define field readers/accessors in GraphQL schema manually after creating a new model/schema.

**Describe the solution you'd like**

I want a generator that creates a graphql schema and generates all field accessors for a given model based on its schema.

**Describe alternatives you've considered**

Manually creating GraphQL schema every time I make new models/schema

**Additional context**

Please feel free to let me know if this already exists!

### PR DESCRIPTION
**Pull request by tadeusz-niemiec**
Resolves #2951

Added support for existing Models in object generator. If a ActiveRecord's class exists the generator will fetch columns info based on Model's schema.

Example usage:

`rails generate graphql:object User`

You can also add custom fields which don't exist in your schema, example:

`rails generate graphql:object User custom_field:String`

Also added support for "datetime" and "date" field types.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion and sorry I've been slow to review it. The change looks good to me, but could you please add some tests for it, so I can be sure not to break it in the future?

**Comment by tadeusz-niemiec** [comment]
> Hi! Thanks for the suggestion and sorry I've been slow to review it. The change looks good to me, but could you please add some tests for it, so I can be sure not to break it in the future?

Done :)

**Comment by rmosolgo** [comment]
Awesome, thanks for this improvement!

**Comment by mmahalwy** [comment]
@tadeusz-niemiec @rmosolgo btw, wanted to highlight this feature as I came across it today by mistake. This is an absolute game changer. Should highlight in the docs!

**Pull request merged**
