### PR TITLE
Update instrumentation.md

### PR DESCRIPTION
**Pull request by dazoakley**
Fix a typo in the code sample

### CODE REVIEW

**Comment by rmosolgo** [comment]
Oopsie! Thanks for pointing this out. The preceeding sample uses`QueryTimerInstrumentation`, should we also use that name here?

**Comment by dazoakley** [comment]
Ah d'oh! Good spot, yep, we should have the same name in both. :)

**Comment by dazoakley** [comment]
And thank you for the awesome gem BTW - it's very useful!

**Comment by dazoakley** [comment]
All updated :)

**Comment by rmosolgo** [comment]
Thanks, just published the changes!

**Pull request merged**
