### PR TITLE
Add operation name for multiple operation queries.

### PR DESCRIPTION
**Pull request by f**
For multi-operation queries, GraphQL Controller throws error on default executor template:

```json
{
  "errors": [
    {
      "message": "An operation name is required"
    }
  ]
}
```

In case of `operationName` sent by client in the query with multi-operation queries, pass `operation_name` to `execute` to avoid this error.

```graphql
# query
query getDiscounts {
  discounts {
    name
  }
}
query getEmployees {
  employees {
    first_name
  }
}
```

I'm sending this query with `operationName=getEmployees` and get the error above. Solved passing `operationName` to the `execute` method. This change may help others not to face this issue again.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: Love it, thanks! Could you update the tests for this generator? I think they just have to match your new code.

**Comment by f** [comment]
Aha sorry, I'll fix them :)

**Comment by f** [comment]
Just saw something wrong with this PR. While updating this branch I pulled upstream to my branch and it created a merge commit. I squashed merge commit into my commit and now it seems I override your commit.

Should I reopen this PR?

**Comment by rmosolgo** [comment]
No problem, I rebased your commits and force-pushed them, I'll merge it when CI passes!

**Pull request merged**
