### PR TITLE
Fix CoercionError handling with null

### LINKED ISSUE #4740: Crash when scalar raises CoercionError on null
**Describe the bug**

When a custom scalar raises a `GraphQL::CoercionError` for an explicit null value on an optional argument, nothing catches the exception or turns it into a response error.

**GraphQL schema**
```ruby
require "graphql"

class CustomScalar < GraphQL::Schema::Scalar
  class << self
    def coerce_input(input_value, _context)
      raise GraphQL::CoercionError, "Invalid value"
    end
  end
end

class QueryType < GraphQL::Schema::Object
  field :hello, String do
    argument :input, CustomScalar, required: false
  end

  def hello(input: nil)
    "hello world"
  end
end

class Schema < GraphQL::Schema
  query(QueryType)
end

result = Schema.execute('{ hello(input: null) }')
puts result.to_json
```

**Expected behavior**

I would expect the above script to print a graphql error response, something like
```
{"errors":[{"message":"Invalid value","locations":[{"line":1,"column":3}],"path":["query","hello","input"],"extensions":{"code":"argumentLiteralsIncompatible","typeName":"CoercionError"}}]}
```

If you pass any value *other* than null into the argument, that is what you get.

**Actual behavior**

The exception bubbles to the top and the program crashes.

<details>
<summary>Click to view exception backtrace</summary>

```
./sample.rb:6:in `coerce_input': Invalid value (GraphQL::CoercionError)
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/argument.rb:260:in `coerce_into_values'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:283:in `block (3 levels) in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:281:in `block (2 levels) in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:280:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:280:in `block in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:309:in `coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/arguments_cache.rb:49:in `dataload_for'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:271:in `evaluate_selection'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:214:in `block (2 levels) in evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:212:in `block in evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:211:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:211:in `evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:121:in `block (4 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:709:in `call_method_on_directives'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:120:in `block (3 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:111:in `block (2 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:71:in `tap_or_each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:102:in `block in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:709:in `call_method_on_directives'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:93:in `run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:75:in `block (6 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/tracing/trace.rb:43:in `execute_query'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:74:in `block (5 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:62:in `block (4 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `each_with_index'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `block (3 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:165:in `block (2 levels) in each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:160:in `each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:164:in `block in each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:191:in `call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:163:in `each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:191:in `call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:45:in `block in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:37:in `run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema.rb:1229:in `multiplex'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema.rb:1205:in `execute'
	from ./sample.rb:25:in `<main>'
```

</details>

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #4740

### CODE REVIEW

**Comment by swalkinshaw** [comment]
I'm curious about this change because `CoercionError` went from inheriting `GraphQL::Error` to `ExecutionError` which has different behaviour. `GraphQL::Error` results in an "unhandled" standard error which in our case is returned as a generic "Internal server error". This change means that all `coerce_result` methods returning a `CoercionError` now return a execution error. Was this intentional or just a side effect or re-using some other error handling in `validate_input`?

**Comment by rmosolgo** [comment]
`CoercionError` was _supposed_ to be into a client-facing error all along, see for example: 

https://github.com/rmosolgo/graphql-ruby/blob/c2e666dc955306802ca5ce31ab1b47db883c50b0/spec/graphql/schema/scalar_spec.rb#L116-L145

https://github.com/rmosolgo/graphql-ruby/blob/c2e666dc955306802ca5ce31ab1b47db883c50b0/spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb#L336-L349

https://github.com/rmosolgo/graphql-ruby/blob/c2e666dc955306802ca5ce31ab1b47db883c50b0/spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb#L183-L192

https://github.com/rmosolgo/graphql-ruby/blob/c2e666dc955306802ca5ce31ab1b47db883c50b0/spec/graphql/schema/dynamic_members_spec.rb#L138-L158

So I thought that by inheriting from `ExecutionError`, I could get some of that `rescue ...`. behavior for free.

If there were cases where CoercionError propagated all the way up the stack (and apparently there were...), they were due to an oversight on my part. Do you have backtraces for them? I'd love to figure out what changed here and, if necessary, we could come up with a plan for compatibility.

**Comment by swalkinshaw** [comment]
I think this is partly due to a single `CoercionError` being used for both `coerce_input` and `coerce_result` but they _can_ be semantically different. For input it should obviously be a client error because they supplied the value. But in our case for `coerce_result` the server is responsible for coercion and returning that result so it's not a client error (most of the time) and we, as the developers, treat these as exceptions which should be fixed.

Here's a backtrace of a `CoercionError` that was raised in a scalar's `coerce_result`:

```plain
["/some/path/id_type.rb:21:in `coerce_result'",
 "gems/graphql-ruby-284542f2c94f/lib/graphql/execution/interpreter/runtime.rb:563:in `continue_field'",
 "gems/graphql-ruby-284542f2c94f/lib/graphql/execution/interpreter/runtime.rb:374:in `block (2 levels) in evaluate_selection_with_resolved_keyword_args'",
```

It was being handled here: https://github.com/rmosolgo/graphql-ruby/blob/04104f17b7bb2b885494bd8c9b2cec33f8f95b83/lib/graphql/execution/interpreter/runtime.rb#L572-L574

Now that it's an `ExecutionError`, it won't go through that code path.

**Comment by rmosolgo** [comment]
Oh... `CoercionError` on _outgoing_ values -- yes, agreed that it's a bug from using the same error in both cases. 

That's in a custom scalar, right? I'm trying to see if `CoercionError` is used that way in GraphQL-Ruby, or documented for that use, and I can't find one in the source. 

The mention in the docs only addresses _incoming_ values: https://github.com/rmosolgo/graphql-ruby/blob/04104f17b7bb2b885494bd8c9b2cec33f8f95b83/guides/type_definitions/scalars.md?plain=1#L101

Maybe the best thing here is to replace that usage of `CoercionError` with something plain-Ruby, like an ArgumentError (or something custom to that scalar?) which would be handled by `rescue_from`. Would that approach work for you?

If it does, I'll improve the docs to suggest that approach for validating _outgoing_ values.

**Comment by swalkinshaw** [comment]
> That's in a custom scalar, right?

Yep custom. We can definitely just raise another error that doesn't inherit from `ExecutionError` so we'll do that regardless. Mainly just wanted to see if this original change was intentional or not. Thanks for talking through it.

**Comment by swalkinshaw** [comment]
One other wrinkle to this... a lot of our scalars implement logic like this:

```ruby
class SomeScalar
  def coerce_input(value, context)
    return if value.nil?

    validate_value(value, context)
    value
  end

  def coerce_result(value, context)
    validate_value(value, context)
    value
  end

  private

  def validate_value(value, context)
    unless value.something
      raise GraphModel::CoercionError, "invalid value #{value}"
    end
  end
end
```

This worked great as is but now we'd have to specify which error gets raised in each case. Again, not a huge deal but just wanted to point out our usage.

**Pull request merged**
