### PR TITLE
CodeClimate v2 configuration

### PR DESCRIPTION
**Pull request by olleolleolle**
- see https://docs.codeclimate.com/docs/advanced-configuration

Or, more exactly: https://docs.codeclimate.com/docs/advanced-configuration#section-analysis-configuration-versions

### CODE REVIEW

**Comment by olleolleolle** [comment]
@rmosolgo Hi, this PR adds the V2 variant of the CodeClimate configuration to the repo, which stops the badge in the README from being _gray_ (due to a build failure on one of the files which are now in the "exclude pattern" list.

**Comment by rmosolgo** [comment]
Oh, that would be nice! I tried to debug but I never made it that far. Here are the results for this branch, but it looks like it still failed: 

https://codeclimate.com/github/rmosolgo/graphql-ruby/builds/138

Maybe we should exclude another file?

**Comment by olleolleolle** [comment]
@rmosolgo Yes! It got there!

**Comment by rmosolgo** [comment]
🎉  Awesome, thank you for figuring this out!

**Pull request merged**
