### PR TITLE
`Schema::Field`: add `#relay_nodes_field` attr reader

### PR DESCRIPTION
**Pull request by FunkyloverOne**
Resolves https://github.com/rmosolgo/graphql-ruby/issues/4101

### CODE REVIEW

**Comment by FunkyloverOne** [comment]
Hey @rmosolgo, would you please add this to both v2.x and v1.13.x? :grin:

**Comment by rmosolgo** [comment]
Thanks for the fix on this! Yes, I'll backport this to 1.13.x after merging and report back here when it's released.

**Comment by FunkyloverOne** [comment]
Hey @rmosolgo, any chance you could also address this bug in the following release? :sweat_smile: 
https://github.com/rmosolgo/graphql-ruby/issues/4106

**Comment by rmosolgo** [comment]
Added to 1.13.x in 18953aa85

**Comment by rmosolgo** [comment]
and shipped 1.13.14 :+1:

**Pull request merged**
