### PR TITLE
Improve lexing performance by generating lexer with Ragel 7.0.0.9 and avoiding lambda in token emission

### PR DESCRIPTION
**Pull request by ivoanjo**
While investigating why query lexing was measurably slower in JRuby than with MRI (see https://github.com/jruby/jruby/issues/4623 ) I noticed that GraphQL's lexer seemed to be generated with Ragel 6.

I then noticed that this version was rather old and that a newer Ragel 7 seemed to have a lot of improvements on the Ruby output backend, even adding four different output options for generated lexers:

* `-T0` Binary search (default)
* `-T1` Binary search with expanded actions
* `-F0` Flat table
* `-F1` Flat table with expanded actions

Testing all four of these combinations and comparing with the current GraphQL lexer on both MRI and JRuby showed that for a lexing-only benchmark (included below), Ragel 7's `-F1` improved MRI peformance by 87% and JRuby performance by 263%:

* MRI before:

```
Running with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Warming up --------------------------------------
               Lexer   111.000  i/100ms
Calculating -------------------------------------
               Lexer      1.124k (± 3.9%) i/s -     33.744k in
30.069500s
```

* MRI after:

```
Running with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Warming up --------------------------------------
               Lexer   209.000  i/100ms
Calculating -------------------------------------
               Lexer      2.102k (± 3.0%) i/s -     63.118k in
30.052143s
```

* JRuby before:

```
Running with jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM)
64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer    24.000  i/100ms
Calculating -------------------------------------
               Lexer    250.435  (± 4.8%) i/s -      7.512k in
30.080584s
```

* JRuby after:

```
Running with jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM)
64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer    88.000  i/100ms
Calculating -------------------------------------
               Lexer    910.242  (± 3.0%) i/s -     27.280k in
29.999337s
```

Unfortunately, this does not yet bring JRuby performance to MRI's level, and I plan to continue looking at how to improve this.

An important note is that the latest Ragel 7 release drops support for a lot of languages, unfortunately including Ruby (see https://www.colm.net/news/2016/07/31/ragel-target-langs.html for the announcement) so the last currently-available Ragel 7 version that can be used is 7.0.0.9, which was the version I used.

Lexing benchmark used to obtain the numbers above:

```ruby
require 'graphql'
require 'benchmark/ips'

input_string = "{
  viewer {
    login
    starredRepositories {
      totalCount
    }
    repositories(first: 3) {
      edges {
        node {
          name
          stargazers {
            totalCount
          }
          forks {
            totalCount
          }
          watchers {
            totalCount
          }
          issues(states:[OPEN]) {
            totalCount
          }
        }
      }
    }
  }
}
"

puts "Running with #{RUBY_DESCRIPTION}"

Benchmark.ips do |benchmark|
  benchmark.time = 30
  benchmark.warmup = 30
  benchmark.report('Lexer') {
GraphQL::Language::Lexer.tokenize(input_string) }
  benchmark.compare!
end
```

# Update: Also get rid of lambda for emitting tokens

This has a small impact on MRI:

```
Running with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Warming up --------------------------------------
               Lexer   211.000  i/100ms
Calculating -------------------------------------
               Lexer      2.121k (± 3.3%) i/s -     63.722k in  30.080212s
```

But a **HUGE** impact on JRuby:

```
Running with jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM)
64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer   372.000  i/100ms
Calculating -------------------------------------
               Lexer      4.078k (± 5.0%) i/s -    122.016k in  30.008956s
```

Especially when using the `-Xcompile.invokedynamic=true` option:

```
Running with jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM)
64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +indy +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer   800.000  i/100ms
Calculating -------------------------------------
               Lexer      9.649k (± 7.9%) i/s -    287.200k in  30.009197s
```

Note that in the master branch, JRuby with `-Xcompile.invokedynamic=true` is the worst performing option (clocking in at about 141k i/s), so with this PR it goes from slowest option to being the fastest by far, with a speedup of about 68x.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Wow, thank you so much for looking into this! I saw the news about removing Ruby support from Ragel 7, so I thought we would just stay on Ragel 6 forever. Now, I see that the earliest versions of Ragel 7 _do_ have Ruby support, so we can at least use _that_ for a while! 

Also, reading up on your exploring with JRuby, let me try to refactor out that lambda. I think it can be handled a bit better, I really didn't understand Ragel's setup well when I wrote this the first time!

**Comment by ivoanjo** [comment]
@rmosolgo the lambda definitely makes a difference! I was just testing it out now:

```diff
diff --git a/lib/graphql/language/lexer.rl b/lib/graphql/language/lexer.rl                                                                      
index 4dd2439d..717bab62 100644                                                                                                                 
--- a/lib/graphql/language/lexer.rl                                                                                                             
+++ b/lib/graphql/language/lexer.rl                                                                                                             
@@ -49,40 +49,40 @@                                                                                                                             
   UNKNOWN_CHAR =         /./;                                                                                                                  
                                                                                                                                                
   main := |*                                                                                                                                   
-    INT           => { emit_token.call(:INT) };                                                                                                
-    FLOAT         => { emit_token.call(:FLOAT) };                                                                                              
-    ON            => { emit_token.call(:ON) };                                                                                                 
-    FRAGMENT      => { emit_token.call(:FRAGMENT) };                                                                                           
-    TRUE          => { emit_token.call(:TRUE) };                                                                                               
-    FALSE         => { emit_token.call(:FALSE) };                                                                                              
-    NULL          => { emit_token.call(:NULL) };                                                                                               
-    QUERY         => { emit_token.call(:QUERY) };                                                                                              
-    MUTATION      => { emit_token.call(:MUTATION) };
-    SUBSCRIPTION  => { emit_token.call(:SUBSCRIPTION) };
-    SCHEMA        => { emit_token.call(:SCHEMA) };
-    SCALAR        => { emit_token.call(:SCALAR) };
-    TYPE          => { emit_token.call(:TYPE) };
-    IMPLEMENTS    => { emit_token.call(:IMPLEMENTS) };
-    INTERFACE     => { emit_token.call(:INTERFACE) };
-    UNION         => { emit_token.call(:UNION) };
-    ENUM          => { emit_token.call(:ENUM) };
-    INPUT         => { emit_token.call(:INPUT) };
-    DIRECTIVE     => { emit_token.call(:DIRECTIVE) };
-    RCURLY        => { emit_token.call(:RCURLY) };
-    LCURLY        => { emit_token.call(:LCURLY) };
-    RPAREN        => { emit_token.call(:RPAREN) };
-    LPAREN        => { emit_token.call(:LPAREN) };
-    RBRACKET      => { emit_token.call(:RBRACKET) };
-    LBRACKET      => { emit_token.call(:LBRACKET) };
-    COLON         => { emit_token.call(:COLON) };
+    INT           => { emit(:INT, ts, te, meta) };
+    FLOAT         => { emit(:FLOAT, ts, te, meta) };
+    ON            => { emit(:ON, ts, te, meta) };
+    FRAGMENT      => { emit(:FRAGMENT, ts, te, meta) };
+    TRUE          => { emit(:TRUE, ts, te, meta) };
+    FALSE         => { emit(:FALSE, ts, te, meta) };
+    NULL          => { emit(:NULL, ts, te, meta) };
+    QUERY         => { emit(:QUERY, ts, te, meta) };
+    MUTATION      => { emit(:MUTATION, ts, te, meta) };
+    SUBSCRIPTION  => { emit(:SUBSCRIPTION, ts, te, meta) };
+    SCHEMA        => { emit(:SCHEMA, ts, te, meta) };
+    SCALAR        => { emit(:SCALAR, ts, te, meta) };
+    TYPE          => { emit(:TYPE, ts, te, meta) };
+    IMPLEMENTS    => { emit(:IMPLEMENTS, ts, te, meta) };
+    INTERFACE     => { emit(:INTERFACE, ts, te, meta) };
+    UNION         => { emit(:UNION, ts, te, meta) };
+    ENUM          => { emit(:ENUM, ts, te, meta) };
+    INPUT         => { emit(:INPUT, ts, te, meta) };
+    DIRECTIVE     => { emit(:DIRECTIVE, ts, te, meta) };
+    RCURLY        => { emit(:RCURLY, ts, te, meta) };
+    LCURLY        => { emit(:LCURLY, ts, te, meta) };
+    RPAREN        => { emit(:RPAREN, ts, te, meta) };
+    LPAREN        => { emit(:LPAREN, ts, te, meta) };
+    RBRACKET      => { emit(:RBRACKET, ts, te, meta) };
+    LBRACKET      => { emit(:LBRACKET, ts, te, meta) };
+    COLON         => { emit(:COLON, ts, te, meta) };
     QUOTED_STRING => { emit_string(ts + 1, te - 1, meta) };
-    VAR_SIGN      => { emit_token.call(:VAR_SIGN) };
-    DIR_SIGN      => { emit_token.call(:DIR_SIGN) };
-    ELLIPSIS      => { emit_token.call(:ELLIPSIS) };
-    EQUALS        => { emit_token.call(:EQUALS) };
-    BANG          => { emit_token.call(:BANG) };
-    PIPE          => { emit_token.call(:PIPE) };
-    IDENTIFIER    => { emit_token.call(:IDENTIFIER) };
+    VAR_SIGN      => { emit(:VAR_SIGN, ts, te, meta) };
+    DIR_SIGN      => { emit(:DIR_SIGN, ts, te, meta) };
+    ELLIPSIS      => { emit(:ELLIPSIS, ts, te, meta) };
+    EQUALS        => { emit(:EQUALS, ts, te, meta) };
+    BANG          => { emit(:BANG, ts, te, meta) };
+    PIPE          => { emit(:PIPE, ts, te, meta) };
+    IDENTIFIER    => { emit(:IDENTIFIER, ts, te, meta) };
     COMMENT       => { record_comment(ts, te, meta) };
 
     NEWLINE => {
@@ -92,7 +92,7 @@
 
     BLANK   => { meta[:col] += te - ts };
 
-    UNKNOWN_CHAR => { emit_token.call(:UNKNOWN_CHAR) };
+    UNKNOWN_CHAR => { emit(:UNKNOWN_CHAR, ts, te, meta) };
 
   *|;
 }%%
@@ -136,10 +136,6 @@ module GraphQL
 
         %% write init;
 
-        emit_token = ->(name) {
-          emit(name, ts, te, meta)
-        }
-
         %% write exec;
 
         meta[:tokens]
```

and JRuby finally kicked into gear:

```
Running with jruby 9.1.11.0-SNAPSHOT (2.3.3) 2017-05-26 ebc009d Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer   350.000  i/100ms
Calculating -------------------------------------
               Lexer      3.777k (± 4.1%) i/s -    113.400k in  30.074892s
```

and JRuby with invokedynamic went from being the worst configuration to being the best:

```
Running with jruby 9.1.11.0-SNAPSHOT (2.3.3) 2017-05-26 ebc009d Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +indy +jit [linux-x86_64]
Warming up --------------------------------------
               Lexer   826.000  i/100ms
Calculating -------------------------------------
               Lexer      9.994k (± 4.5%) i/s -    299.012k in  29.986866s
```

MRI is still mostly the same performance as with my measurements above:

```
Running with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Warming up --------------------------------------
               Lexer   205.000  i/100ms
Calculating -------------------------------------
               Lexer      2.071k (± 4.2%) i/s -     62.115k in  30.048881s
```

I wasn't expecting it to be "this easy", and that's why I decided to open the PR while I explored other options, but perhaps it is this easy.

What do you think? Shall I add also this change to this PR, or should I submit a separate one?

**Comment by rmosolgo** [comment]
Adding it here is good by me!

**Comment by rmosolgo** [comment]
(Lol, I'm still trying to install Ragel 7. I'm out of my depth when `brew install` doesn't ✨  Just work ✨ )

**Comment by ivoanjo** [comment]
Yeap, took me a while to get it installed to. I'm on linux, but can't remember the last time I had to `./configure`, `make`, `make install`. Also a gotcha that bit me yesterday is that you need to have [this](https://www.colm.net/files/colm/colm-0.13.0.4.tar.gz) exact colm version installed.

I'm going to update the PR then!

**Comment by rmosolgo** [comment]
```
$ ragel -v
Ragel State Machine Compiler version 7.0.0.9 August 2016
Copyright (c) 2001-2015 by Adrian Thurston
```

💰 ! 

I will add a bit to the docs about installing Ragel.

**Comment by ivoanjo** [comment]
@rmosolgo pushed my changes, let me know what you think!

I'm pretty excited about these results, they are a lot more than I expected from 1.5 days' work :)

**Comment by rmosolgo** [comment]
🤘  So great! Thanks again for diving into the lexer. Personally, I find it one of the most intimidating parts of the project 😅 

I'll cut a version soon, I think I have one more thing to sneak in there.

**Comment by rmosolgo** [comment]
Released in 1.5.14!

**Pull request merged**
