### PR TITLE
Add GraphQL::Pro documentation

### PR DESCRIPTION
**Pull request by rmosolgo**
I'm [starting a new component of this project](http://rmosolgo.github.io/blog/2017/01/09/introducing-graphql-pro/) and I think it makes sense to keep the docs together, at least to get started!

### CODE REVIEW

**Comment by rmosolgo** [comment]
I'd love to hear any questions or comments about this project here on GitHub, on Slack, or any other place :)

**Comment by peterkeen** [comment]
Great idea! Love the authorization stuff, that was half of my flailing while setting up our initial schema Still haven't gotten all the way there and will likely abandon in favor of Pro.

**Comment by rmosolgo** [comment]
Cool, I'd love to hear how it fits for you if you get a chance to try it! It seemed like a nice opportunity to unify a few different extension points in the gem.

**Comment by bgentry** [comment]
FYI the docs link to https://graphql.pro but your HTTPS is misconfigured (github doesn't support custom domains). Maybe try CloudFlare for free TLS?

**Comment by rmosolgo** [comment]
Derp, thanks for the heads up! I've switched it back to `http` for now.

**Pull request merged**
