### PR TITLE
Add Connection.nodes shorthand

### PR DESCRIPTION
**Pull request by josh**
While the `Connection`/`Edge`/`Node` model provides a useful place to attach join model annotations, most of @github's usage has just been enumerating a connection's node list. Cursor data is simply accessed via `PageInfo.endCursor`.

This change adds and additional `Connection.nodes` as a shortcut for accessing `Connection->edges->node`.

I understand this isn't part of the Relay spec specifically, so maybe it could be opt-in if you think its  necessary?

I'm hoping I'm remember this right, but I believe @dschafer (@facebook) mentioned this alias to me at a GraphQL conference/meetup thing.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Yeah, I think opt-in is a good choice, that way people who track changes via a schema printout don't get a bunch of noise when they update. Maybe in a later version, we can make this the default behavior and allow people to opt _out_.

**Comment by josh** [comment]
> Yeah, I think opt-in is a good choice,

Revised to support `define_connection(nodes_field: true)`.

**Comment by rmosolgo** [comment]
👌 good by me, but one more in case you want it: do you want a default, something like `GraphQL::Relay::ConnectionType.default_nodes_field`, so you can apply this to your whole schema at once? 

Happy to merge as is if you don't want it or you'd rather do it separately.

**Comment by josh** [comment]
> do you want a default, something like GraphQL::Relay::ConnectionType.default_nodes_field

Oh! Great idea. Yep, let me get that in first.

**Comment by josh** [comment]
Added `GraphQL::Relay::ConnectionType.default_nodes_field`. I guess its global for the entire environment. I didn't see a great way to scope it to a schema instance. Doesn't seem so bad though.

**Comment by rmosolgo** [comment]
Good by me!!

**Comment by josh** [comment]
❤️

**Pull request merged**
