### PR TITLE
Make language nodes immutable

### PR DESCRIPTION
**Pull request by tenderlove**
We have code in our client that "deep freezes" all AST nodes.  I think we could eliminate that if we just made AST nodes immutable by default.  I only found one place where the gem is mutating nodes, but I guess all those "writer" methods are public API, so this PR might only be good for a major version release.

I separated this PR to two commits because I think avoiding mutation internally has merit on its own.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: Looks like a nice improvement to me, I want to check tomorrow to make sure it doesn't break graphql-client, but other than that,  I think it's all clear!

**Comment by rmosolgo** [comment]
Somehow I thought I already merged this, but I didn't 😌 

It's going to break graphql-client: 

https://github.com/github/graphql-client/blob/master/lib/graphql/client/query_typename.rb#L21-L34

I like the idea of a more stable AST structure, but I'm going to change the target of this PR to `1.8-dev` and merge it in a bit, when I have some time to update that code as well.

**Comment by tenderlove** [comment]
I'll look in to what it takes to make graphql-client *not* mutate nodes.  We may need a more functional interface for manipulating ASTs.

**Comment by rmosolgo** [comment]
GraphQL-js has a really nice approach for this, I added a comment to the previous issue for improving AST manipulation: https://github.com/rmosolgo/graphql-ruby/issues/455#issuecomment-373472078

**Comment by rmosolgo** [comment]
There are still a few things to do before immutable nodes are _really_ ready: 

- consider freezing the arrays that make up`.children`, too, so it doesn't get changed underfoot (then `.children` could also be frozen)
- add `Node#path` (and maybe `Node#parent`?) to simplify working with the AST, and it can be quite efficient now that they're frozen 
- improve Visitor (see #1290) to support manipulating the AST, so people have a new way of messing with hand-rolled ASTs

But this is a great first step, so merging into the dev branch!

**Pull request merged**
