### PR TITLE
Ensure there are no spaces after lambda arrows throughout the code

### PR DESCRIPTION
**Pull request by astorije**
This cop was added to RuboCop by https://github.com/bbatsov/rubocop/pull/3656.

This PR ensures #313 will be consistently enforced. It was discussed in #306, #326 and #320.

_**Caveat:** ~~I'm jumping the gun a bit here because that PR wasn't merged yet~~, nor RuboCop's next version was release, but at least my PR will be ready as soon as these happen. I'll be rebasing this PR accordingly.
**Edit:** PR was merged, no new release yet._

### CODE REVIEW

**Comment by cjoudrey** [comment]
The PR just got merged.

We _could_ do this while we wait for them to cut a new release:

```ruby
gem :rubocop, git: 'https://github.com/bbatsov/rubocop.git', ref: 'a94bef08e0559d0037b368037aa8cbac01e3fe94'
```

**Comment by astorije** [comment]
@cjoudrey, updated this PR to use final cop name.
Also added your git ref to let Travis have fun with it, but I don't think this PR should be merged until a release. It's not that critical anyway.

**Comment by cjoudrey** [comment]
> but I don't think this PR should be merged until a release. It's not that critical anyway.

Good point. Even if new occurrences get added, the new cop has autocorrect support so it'll be easy to fix them.

**Comment by rmosolgo** [comment]
How's this branch doing? Did we get a Rubocop release yet?

**Comment by astorije** [comment]
That's my bad, I completely dropped the ball on this. Let me get back to it
when I have a little bit of spare time.

**Comment by rmosolgo** [comment]
I've: 

- rebased on master 
- updated the gemspec to point at a release 
- fixed offending code (well, `rubocop -a` did the work :P )

Thanks for this contribution!

**Comment by astorije** [comment]
Urgh, I am truly the worst!! Very sorry about that and thank you very much for taking over this PR, @rmosolgo!

**Comment by rmosolgo** [comment]
Not at all, thanks for doing the heavy lifting here!

**Pull request merged**
