### PR TITLE
Account for list of errors when performing field instrumentation.

### PR DESCRIPTION
**Pull request by stanishev**
Looking to address the issue described: [2566](https://github.com/rmosolgo/graphql-ruby/issues/2566)

### CODE REVIEW

**Comment by stanishev** [comment]
@rmosolgo Would appreciate a brief pointer regarding where and how to write the specs for this fix.. 😬 
can do over slack.

**Comment by sasharevzin** [comment]
@rmosolgo Thank you for the suggestion; we just added the spec
Let us know if more changes are needed.

**Comment by sasharevzin** [comment]
@rmosolgo This is now ready for review. Thank you

**Comment by rmosolgo** [comment]
Awesome, thanks for your work on this 🎉 !

**Pull request merged**
