### PR TITLE
Add unscope(:order) to relation count on relay

### PR DESCRIPTION
**Pull request by sideshowdave7**
Passing in ordered relations to Graphql Relay can give undesirable results as seen in issue #1353 

Doing this, or adding an option to unorder the relation before counting would be extremely useful.

My use case for this is ordering on joined tables makes counts in MySQL really slow.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Thanks for the fix, it looks good! Should we do anything to test it?

**Comment by sideshowdave7** [comment]
I'd be happy to do that, any pointers on where to write a test for this?

**Comment by mazikwyry** [comment]
@rmosolgo ping. I have the same issue after migrating an app from MySQL to Postgres and would be great to have that fix released.

The easiest way to test that would be to check if `.order("table_name.attrubute DESC")` works when asking for `total_count` in the query. (note it works for the first page and the last page, you have to have at least 3 pages).

**Comment by rmosolgo** [comment]
Hey, sorry for leaving this hanging and not recommending a place to test 😞  I just pushed a test myself and I'll get this rolled into the next release!

**Comment by sideshowdave7** [comment]
@rmosolgo Thanks for doing that!

**Pull request merged**
