### PR TITLE
Implement new `ConnectionResolve` class

### PR DESCRIPTION
**Pull request by gjtorikian**
This class simply performs the duties of the proc expected of a connection resolver. However, by using a class, you can easily identify whether or not a field is a connection by inspecting the `resolve_proc` of a field.

Closes https://github.com/rmosolgo/graphql-ruby/issues/201.

### CODE REVIEW

**Comment by rmosolgo** [comment]
💰 !!! Thanks!

**Comment by gjtorikian** [comment]
Yessss. Can I get that sweet sweet gem release? 🙏🏽

**Comment by rmosolgo** [comment]
🍰 0.18.1 🍨

**Comment by gjtorikian** [comment]
Amazing. Thank you!

**Pull request merged**
