### PR TITLE
Add Guides for Datadog Tracing

### PR DESCRIPTION
**Pull request by maxcodes**
Ok, so that happened way faster than I expected 🙂 

Adds documentation for the already-added Datadog tracing. 🎉

### CODE REVIEW

**Comment by maxcodes** [comment]
Ah, I thought it was just boilerplate. Should I remove it? It looks weird on Github anyway

**Comment by rmosolgo** [comment]
:+1: Yep, removing it sounds good to me!

**Comment by maxcodes** [comment]
Done 👍

**Comment by rmosolgo** [comment]
Thanks! Just published the update.

**Pull request merged**
