### PR TITLE
Implements .fetch on Arguments

### PR DESCRIPTION
**Pull request by esjee**
A suggested solution to https://github.com/rmosolgo/graphql-ruby/issues/453. Let me know what you think!

### CODE REVIEW

**Comment by mvgijssel** [comment]
LGTM @Willianvdv plz accept.

**Comment by esjee** [comment]
Before merging this, I think it might be interesting to look at some way to use methods instead. So:

```
args.id
```

rather than

```
args[:id]
```

**Comment by rmosolgo** [comment]
Just to give my two cents, in my opinion, the _behavior_ is right but the _name_ is off. 

`Hash#fetch(key)` raises an error if `key` isn't present in the hash. But, the `#fetch` method introduced here _may not_ raise if the argument is defined by not present. I'm hesitant about using the same method name to describe different behavior. 

So, what name could we give this method?

```ruby 
args.get(:something) # ? 
args[:something] # change the behavior of this? could be breaking? 
args.something # use method call syntax for this behavior?
```

Method calls sound promising, but to avoid `method_missing`, we'd have to generate a classes at schema build time!

**Comment by volkanunsal** [comment]
@rmosolgo This sounds like an OpenStruct. I always wrap my args in an [`immutable-struct`](https://github.com/stitchfix/immutable-struct). It provides a nice immutable implementation of an OpenStruct, sans the assignment operator, and has a [simple implementation](https://github.com/stitchfix/immutable-struct/blob/master/lib/immutable-struct.rb).

```ruby
args = ImmutableStruct.new(:foo)
args.new(foo: 1)
args.foo
# => 1
args.foo = 1
NotMethodError
```

**Comment by rmosolgo** [comment]
yes, very similar, _except_ we can define all the methods ahead of time, since we know the schema!

**Comment by esjee** [comment]
#924 seems more promising, closing this one out

**Pull request closed without merging**
