### PR TITLE
Make a website

### PR DESCRIPTION
**Pull request by rmosolgo**
I'm not a very visual person, but I still want a website for a few reasons: 

- Make guides more navigable (todo: `<a>` for each header)
- Room to expand (for example, I'd like to make detailed guides for each GraphQL type or serve API docs from the site)
- Show off the cool logo 

So, I've tried to kick off the process for a website in this branch. However, I'm not very good at making things look nice. So, if someone with those skills wants to help out, I'd really appreciate that! My only requirements are: 

- Docs must be easy to find, easy to navigate and easy to read 
- The less JavaScript the better
- Deploy must be completely automated
- Code must be highlighted

All that said, here's how it looks now: 

image

## TODO 

- [x] fix gemspec (?) with site dependencies 
- [x] figure out the right way of handling `graphql-ruby/` prefix on gh-pages
- [ ] make the deploy process right (see nanoc docs?)
- [ ] get the logo on the header

### CODE REVIEW

**Comment by gjtorikian** [comment]
> make the deploy process right

I can definitely help out here (or anywhere else, really). I built most of the stuff for https://github.com/github/developer.github.com and have a lot of experience with nanoc-based sites.

**Comment by rmosolgo** [comment]
[image](http://www.theonion.com/article/nation-finally-breaks-down-and-begs-its-smart-peop-26450)

Srsly I have no idea what to do here! 

I was reading [nanoc docs for gh-pages](http://nanoc.ws/doc/deploying/#with-github-pages-or-bitbucket) but if understood it right, it's assuming that the website is in a different repo than the main project, is that right? I'd really like to keep the docs in the main repo (so they're always in sync with the code). Is it possible to do it that way? 

I'll take anything: link to a blog post, instructions on what to do, PR to this branch, whole new branch with a better setup, anything! What do you think?

**Comment by gjtorikian** [comment]
I'll probably make a PR into this branch if that's cool.

You can keep a directory for just the nanoc site content. I think what you're missing is setting up the nanoc.yml config vars to point out that you want a subdirectory built, not the default assumption that the root is the entire site.

**Comment by rmosolgo** [comment]
I'm gonna start over with jekyll & the new github pages support for the `/docs` folder

**Comment by gjtorikian** [comment]
👍

**Pull request closed without merging**
