### PR TITLE
return false for hasNextPage when using last: qualifier

### PR DESCRIPTION
**Pull request by geneeblack**
I can think of no conditions where hasNextPage would ever be other than false when last:n is used

### CODE REVIEW

**Comment by rmosolgo** [comment]
I think `hasNextPage` may be true in a case like this: 

```ruby
# given these items: 
[a, b, c, d, e, f, g]
#      |--|
items(last: 2, before: e)
# => nodes [c, d]
#    hasPreviousPage: true 
#    hasNextPage: true
```

What do you think?

**Comment by geneeblack** [comment]
I would think that given the last 2 before e there would be no next page as long as the before e statement was in effect since there could be no items on the next page that are before e.

**Comment by geneeblack** [comment]
Ah, yah. I guess that's a little heavy handed to ensure last returns a false when not using before/after. maybe the second commit will address that edge case better.

**Comment by rmosolgo** [comment]
Thanks for the update, I see the tests are passing now (sorry about the JRuby situation, JRuby is a constant struggle). Can you add a test which demonstrates the bug, or describe the case where you noticed this issue? I want to make sure we don't introduce a regression in this area in the future!

**Comment by olleolleolle** [comment]
@geneeblack The JRuby tests are green on current master - could you try on top of that?

**Pull request closed without merging**
