### PR TITLE
Merge graphql relay into graphql

### PR DESCRIPTION
**Pull request by daqo**
This PR merges graphql-relay-ruby gem into graphql-ruby gem while preserving the history of both projects.

1. Lib, Spec and Changelog files are copied from graphql-relay-ruby into graphql-ruby.
2. README for relay project has been moved under /guides.
2. The tests are passing.
3. I also integrated the final version into the GraphQL/Relay project that I am currently working on with no problem.This PR merges graphql-relay-ruby gem into graphql-ruby gem while presetving the history of both projects.

1. Lib, spec and Changelog are copied from graphql-relay-ruby into graphql-ruby.
2. README for relay project has been moved under /guides.
2. The tests are passing.
3. I also integrated the final version into the GraphQL/Relay project that I am currently working on with no problem.

### CODE REVIEW

**Comment by rmosolgo** [comment]
:tada: wow!! let me see if I can get CI going with the new stuff...

**Comment by rmosolgo** [comment]
Ok, tried to update the docs and CI a bit here: 

https://github.com/daqo/graphql-ruby/pull/1

If that looks ok to you & you merge it here, it should trigger the CI again and we'll see how it does ...

**Comment by rmosolgo** [comment]
Hmmm, I see there's a commit especially _for_ Rails 3.2. I'll add the Appraisal back later, it will require Travis `matrix:` (The Right Way :tm: :P )

**Comment by rmosolgo** [comment]
[` ArgumentError: method 'select_all': given 4, expected 4`](https://travis-ci.org/rmosolgo/graphql-ruby/jobs/148737100#L3831)

/me scratches head

**Comment by rmosolgo** [comment]
Maybe a buggy Rbx version? https://github.com/globalize/globalize/pull/512#issuecomment-227184463

**Comment by daqo** [comment]
I merged your changes. Trying to figuring out what CI is failing :-/

**Comment by rmosolgo** [comment]
No worries, I'll mess with it on master. THANK YOU!!

By the way, what did  you have to do to make this work!?

**Comment by daqo** [comment]
Nice. Thank you.
This was the process:

```
1. $ git clone https://github.com/rmosolgo/graphql-relay-ruby
2. $ cd graphql-relay-ruby
3. $ mkdir graphql-relay-ruby
4. Move all files and directories to the newly created folder
5. $ git commit -m 'commit message'
6. $ cd ..
7. $ git clone https://github.com/daqo/graphql-ruby
8. $ cd graphql-ruby
9. $ git remote add graphql-relay-ruby {path_to_grapql-relay-ruby_dir_on_my_local}
10. $ git pull graphql-relay-ruby master
11. $ git remote rm source_repo_name

```

This will bring graphql-relay-ruby as a subdirectory to graphql and preserves history. From this point, it was just a matter of organizing files and directories.

**Comment by daqo** [comment]
@rmosolgo also the links to "Code Reuse", "Relay" and "Security" guides on README.md are broken.

**Comment by rmosolgo** [comment]
Wow, clever! 

Thanks for the heads up on those guides -- I triggered a rebuild on Rubydoc.info, looks good now

**Pull request merged**
