### PR TITLE
Mention dataloader as other batching solution

### PR DESCRIPTION
**Pull request by sheerun**
Disclaimer: I'm an author.

[facebook/dataloader](https://github.com/facebook/dataloader) accepted my solution as alternative implementation of their library, so I though I could add it here as well.

Dataloader tries to mimic facebook/dataloader api as best as possible. In contrast to `batch-graphql` it offers more general solution that can be used even without graphql-ruby. The loaders created with `dataloader` also compose better as their return type is A+ [promise](https://github.com/lgierth/promise.rb).

EDIT: Link for better access:
https://github.com/sheerun/dataloader

### CODE REVIEW

**Comment by ianks** [comment]
This is a javascript library, yeah? It might not be fit for mentioning alongside `graphql-batch`, which is a Ruby implementation.

**Comment by rmosolgo** [comment]
I think it's a _Ruby_ implementation of the same idea. Let me just take a quick look before merging, it looks really cool!

**Comment by sheerun** [comment]
Indeed, it is Ruby implementation with very similar API to the original.

**Comment by rmosolgo** [comment]
Thanks for the update!

**Pull request merged**
