### PR TITLE
Rescue StandardError on graphql controller.

### PR DESCRIPTION
**Pull request by the-harry**
This PR intends to improve the error handling in the generated controller, since rescuing all exceptions may cause some issues.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Sorry, I'm not open to style-only changes. Everyone has a preference, and if there's something you think should be enforced by this code base, I recommend that you open an issue for it first. 

If you're interested in reducing the scope of this change, I agree that adding `StandardError` to the `rescue` condition is a good improvement. I'd be happy to accept that in this pull request or a new one.

**Comment by the-harry** [comment]
> Sorry, I'm not open to style-only changes. Everyone has a preference, and if there's something you think should be enforced by this code base, I recommend that you open an issue for it first.
> 
> If you're interested in reducing the scope of this change, I agree that adding `StandardError` to the `rescue` condition is a good improvement. I'd be happy to accept that in this pull request or a new one.

Alright, makes sense! I'll update it! 😄

**Comment by the-harry** [comment]
@rmosolgo i've updated the PR! Let me know if it's ok!

**Comment by rmosolgo** [comment]
Thanks for the improvement here!

**Pull request merged**
