### PR TITLE
Document passing field to connection class and creating relation object

### PR DESCRIPTION
**Pull request by gauravtiwari**
Add reference to the doc for #213 

Is this good enough?

### CODE REVIEW

**Comment by rmosolgo** [comment]
I think this is covered by #215 , right?

**Comment by gauravtiwari** [comment]
@rmosolgo Yup, but I guess would be good to keep the relation connection part in readme, folks using AR or Sequel might find it useful. What do you think? I can update.

**Comment by gauravtiwari** [comment]
btw @rmosolgo is that new field option needs documenting -  although it's optional?

**Comment by rmosolgo** [comment]
Yes, happy to take an updated patch! If you keep it, I think it's important to mention `field:` separately, after the main example. eg 

> Additionally, connections may be provided with the `GraphQL::Field` that created them. This may be used for custom introspection or instrumentation. For example, ...

I think most people don't actually need it, so I don't want to present it early in the documentation. 

Getting the field from inside the `resolve` proc is not easy, hmm I can think of only a couple ways: 

```ruby 
Schema.get_field(TodoListType, "todos") 
# => #<GraphQL::Field name="todos">
context.irep_node.definitions[TodoListType] 
# => #<GraphQL::Field name="todos">
# although this one may not work with fields on interfaces
```

**Comment by gauravtiwari** [comment]
@rmosolgo there you go. Good enough?

**Comment by rmosolgo** [comment]
💰 👌  Thanks!!

**Pull request merged**
