### PR TITLE
Function docs: update types usage

### PR DESCRIPTION
**Pull request by swalkinshaw**
`types` is exposed in functions as of `1.5.6` (in https://github.com/rmosolgo/graphql-ruby/pull/654)

I figured the whole section on Types wasn't even needed anymore?

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Found two more function related things to update 👌

**Comment by rmosolgo** [comment]
Awesome, thanks for giving this some attention! It looks like the Function generator tests may need an update for the new output as well.

**Comment by swalkinshaw** [comment]
Updated 🎉

**Comment by rmosolgo** [comment]
:metal: published, thanks again!

**Pull request merged**
