### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by ydah**

### CODE REVIEW

**Comment by rmosolgo** [comment]
Thanks! Just a _few_ fixes here 😅 . It looks like the tests broke along the way -- do you mind updating those to pass?

**Comment by ydah** [comment]
Oh, sorry. I updated this PR.

**Comment by rmosolgo** [comment]
Thanks ... almost there!

**Comment by ydah** [comment]
Ah... my bad. I updated this PR :bow:

**Comment by rmosolgo** [comment]
Thanks!

**Pull request merged**
