### PR TITLE
Call prepare on lists of input objects

### PR DESCRIPTION
**Pull request by engwan**
When the argument is a list of input objects we need to call prepare on each item of the list.

### CODE REVIEW

**Comment by engwan** [comment]
@rmosolgo I found a bug related to https://github.com/rmosolgo/graphql-ruby/pull/4902

I'm not sure if there's a better way to check for lists of input objects but I've added a spec to illustrate the bug.

**Comment by rmosolgo** [comment]
Thanks for sharing this fix! Did this _used_ to work before 2.3.1?

**Comment by engwan** [comment]
> Thanks for sharing this fix! Did this _used_ to work before 2.3.1?

Yes, this used to work before 2.3.1 because `coerce_input` called `prepare`.

I am trying to upgrade the GraphQL gem for GitLab and the upgrade broke our tests: https://gitlab.com/gitlab-org/gitlab/-/jobs/6711137035

I did manage to get a workaround working here: https://gitlab.com/gitlab-org/gitlab/-/commit/16e8a1035180f039cf02359b180be799ec813d68. But I think it would be better to have it fixed upstream.

**Comment by rmosolgo** [comment]
Cool, thanks for clarifying. I added a commit to handle lists-of-lists, too! I'm going to investigate one other report of a bug from this change before I release the new version 👀 https://github.com/rmosolgo/graphql-ruby/pull/4902/files#r1579471558

**Comment by engwan** [comment]
Thanks for the quick response!

**Pull request merged**
