### PR TITLE
Fix unicode character escape in literal strings

### PR DESCRIPTION
**Pull request by dylanahsmith**
I found out that [EscapedUnicode](http://facebook.github.io/graphql/#EscapedUnicode) was being treated as valid by the lexer, resulting in a `Parse error on bad Unicode escape sequence` GraphQL::ParseError exception.

### CODE REVIEW

**Comment by rmosolgo** [comment]
I thought to myself "We have [a spec for this](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/compatibility/query_parser_specification.rb#L77), how did _it_ pass?" 

And I see that it's because we're testing the _whole_ string for those patterns, so if the string contains _any_ valid escapes, then it won't be identified as `BAD_UNICODE_ESCAPE`. I've pushed another test to demonstrate the difference. 

In the short term, it seems like that string matching should be more local (ie, it should look at _each_ escape and assert that it is valid). 

In the long term, I'd like to refactor the Lexer to make replacements on the _first_ pass, like libgraphqlparser does. 

(Also, I found this in the meantime! https://github.com/rmosolgo/graphql-ruby/pull/396)

**Comment by dylanahsmith** [comment]
Pushed a fix for the other bug you found with validating character escapes in string tokens.

**Comment by rmosolgo** [comment]
Sweet, thanks!!

**Comment by rmosolgo** [comment]
:ship: in 1.2.4!

**Pull request merged**
