### PR TITLE
Run tests on JRuby

### PR DESCRIPTION
**Pull request by MSNexploder**
This pull requests enables JRuby for all tests on Travis

### CODE REVIEW

**Comment by rmosolgo** [comment]
Wow, awesome!! Thanks for taking a crack at this. It would be great to formally support JRuby.

It looks to me like the failures are unrelated to your changes here, right? Maybe some CI configs just need to be updated (but I wonder why they pass on master ...)

**Comment by rmosolgo** [comment]
Ok, I fixed CI on master, so if you rebase, you should get a proper result!

**Comment by MSNexploder** [comment]
I rebased to the latest master and fixed Travis picking JRuby 1.7 instead of the current 9k builds.

**Comment by rmosolgo** [comment]
Thanks! Wow, strange failures there. I guess we can take a look at those next 😬

**Pull request merged**
