### PR TITLE
Class-based subscription fields

### PR DESCRIPTION
**Pull request by rmosolgo**
The current subscription system leaves a lot to be desired, see for example #1528 #1799 #1910 

I'm proposing a `GraphQL::Schema::Subscription` like `GraphQL::Schema::Mutation` with authorization, initialization, and update methods.

You can see the rendered doc here: https://github.com/rmosolgo/graphql-ruby/blob/good-subscriptions/guides/subscriptions/subscription_classes.md

__TODO__: 

- [x] What if you don't want to update a certain client of an event? (For example, that client _triggered_ the event)

### CODE REVIEW

**Comment by theorygeek** [comment]
Nice! I like it. How do you hook up the transport? I'm assuming there needs to be some method that GraphQL can invoke when an update needs to be sent to a client?

> Then, `def update` will be called for each client's subscription
It is going to send the update to _every_ client by default, and your `update` should return `skip` if that particular client doesn't need the update?

**Comment by rmosolgo** [comment]
Thanks for taking a look! 

> How do you hook up the transport?

That consideration is separated a bit. The changes here revolve around how subscriptions are _evaluated_ by GraphQL, but not how the result is transmitted to clients. 

In terms of transport, the subscription implementation should define [`#deliver` for sending payloads](http://graphql-ruby.org/api-doc/1.8.11/GraphQL/Subscriptions.html#deliver-instance_method) to clients. See [ActionCable's `#deliver`](http://graphql-ruby.org/api-doc/1.8.11/GraphQL/Subscriptions/ActionCableSubscriptions.html#deliver-instance_method) for example.

> _every_ client by default? 

Yes, that's right. I'm glad you mentioned it: it should really have a way to halt, and send _nothing_ to a client if desired, but there's not a way to do that yet. I added a TODO above.

**Comment by modosc** [comment]
> What if you don't want to update a certain client of an event? 

we've hit this a few different times - mostly because of my understanding on how scoping works it's hard to have multidimensional filters (ie, company A + role B). we sometimes end up sending out notifications on a model which is not visible for some clients. if we allow the subscription field to be null, then we send out empty messages to a bunch of clients. my hacky solution was to make the field non-nullable and hide the `Cannot return null for non-nullable field Subscription.foo` error but this isn't great. ideally there'd be some option for "not null for the client but if the server returns null just skip delivery".

**Comment by rmosolgo** [comment]
It's basically implemented as written, feel free to take another look if you're interested! Otherwise I'll merge it tomorrow or so.

**Comment by phyllisstein** [comment]
I'm so excited about this @rmosolgo, thank you for all this amazing work. ✨

**Pull request merged**
