### PR TITLE
Make sure ActionCableHandler only unsubscribes once

### LINKED ISSUE #5086: Unable to find subscription with identifier: {"channel":"GraphqlChannel"} (RuntimeError)
**Describe the bug**

Breaking this out of a discussion on a similar issue, https://github.com/rmosolgo/graphql-ruby/issues/4702.

Very frequently – around a thousand times per day – we see this issue fire in Sentry in production. It's not clear if this aligns with user-facing defects, although we do hear occasional reports of real-time features unexpectedly stopping working until refresh.

**Versions**

```
graphql (1.12.19)
rails (7.1.4)
graphql-pro (1.26.5)
graphql-batch (0.4.3)
```

```
"react-relay": "^15.0.0"
"@rails/actioncable": "^6.1.4"
"graphql-ruby-client": "^1.14.0"
```

**GraphQL schema**

Our subscriptions are handled by ActionCable:
```ruby
class TinesSchema < GraphQL::Schema
  use GraphQL::Subscriptions::ActionCableSubscriptions, broadcast: true
  # …
end
```

We have a straightforward implementation of `GraphqlChannel`, following https://graphql-ruby.org/api-doc/2.0.14/GraphQL/Subscriptions/ActionCableSubscriptions.html.

The frontend is powered by Relay, following the ActionCable guide in https://graphql-ruby.org/javascript_client/relay_subscriptions.

**GraphQL query**

We see these for various subscription queries, here's a random example:

```graphql
subscription newLogSubscription($storyId:ID!) {
  newLog(storyId:$storyId) {
    log {
      action {
        hasLogs,
        id,
        working
      },
      createdAt,
      id,
      inboundEventId,
      level,
      message
    }
  }
}
```

**Steps to reproduce**

Unfortunately, I haven't found a way to reproduce the problem, even when I modify our client-side code to repeatedly dispose of a subscription, as discussed here: https://github.com/rmosolgo/graphql-ruby/issues/4702#issuecomment-2327277240.

**Expected behavior**

No exception.

**Actual behavior**

Here's the full stack trace we see, which appears to match https://github.com/rmosolgo/graphql-ruby/issues/4702.

<details>
<summary>Click to view exception backtrace</summary>

```
RuntimeError: Unable to find subscription with identifier: {"channel":"GraphqlChannel"} (RuntimeError)
  from actioncable (7.1.4) lib/action_cable/connection/subscriptions.rb:77:in `find'
  from actioncable (7.1.4) lib/action_cable/connection/subscriptions.rb:49:in `remove'
  from actioncable (7.1.4) lib/action_cable/connection/subscriptions.rb:20:in `execute_command'
  from actioncable (7.1.4) lib/action_cable/connection/base.rb:100:in `block in handle_channel_command'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actioncable (7.1.4) lib/action_cable/connection/base.rb:99:in `handle_channel_command'
  from actioncable (7.1.4) lib/action_cable/connection/base.rb:92:in `dispatch_websocket_message'
  from actioncable (7.1.4) lib/action_cable/server/worker.rb:58:in `block in invoke'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from actioncable (7.1.4) lib/action_cable/connection/tagged_logger_proxy.rb:28:in `tag'
  from actioncable (7.1.4) lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from actioncable (7.1.4) lib/action_cable/engine.rb:79:in `block (4 levels) in <class:Engine>'
  from activesupport (7.1.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from actioncable (7.1.4) lib/action_cable/engine.rb:74:in `block (3 levels) in <class:Engine>'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `instance_exec'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from activesupport (7.1.4) lib/active_support/callbacks.rb:141:in `run_callbacks'
  from actioncable (7.1.4) lib/action_cable/server/worker.rb:41:in `work'
  from actioncable (7.1.4) lib/action_cable/server/worker.rb:57:in `invoke'
  from actioncable (7.1.4) lib/action_cable/server/worker.rb:52:in `block in async_invoke'
  from concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
  from concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
  from <internal:kernel>:187:in `loop'
  from concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
  from concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
  from concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
```

</details>

### PR DESCRIPTION
**Pull request by rmosolgo**
Trying to fix #5086

### CODE REVIEW

**Comment by rmosolgo** [comment]
This didn't help :S

**Comment by rmosolgo** [comment]
Hey @vbatychko-modeln, sure, I'd be happy to merge and release this -- thanks for sharing what you found!

**Comment by rmosolgo** [comment]
🚢  in graphql-ruby-client v1.14.3. Please let me know if you have any more trouble with it!

**Comment by vbatychko-modeln** [comment]
@rmosolgo I have spent some time debugging that issue with double unsubscriptions. Looks like the problem, at least in my case is as follows. Note that I'm using Urql with ActionCable.

Preconditions:
1. Have one Urql.Client for React application in Urql.Provider
2. Have 2 components, both are using the same subscription. E.g., 
subscription OnMessageReceived {
  messgeReceived {
    message
    time
  }

The problem exposes itself, when first component is unmounting (that triggers also unsubscribe() call), and the second is starting subscription negotiation.

In this case, new handler for second component receives {more: false} AC message, which trigger complete() callback, and I suspect that complete() callback in turn calls unsubscribe(), causing subscription to interrupt negotiation. This leaves second component unsubscribed.

I have reworked initial monkey patch from my previous message to following, which fixes doubled unsubscription calls.
Well, at least, in my case.

```javascript
import { Consumer, Subscription, logger } from "@rails/actioncable"
type ForwardCallback = (...args: any[]) => void

function createUrqlActionCableSubscription(consumer: Consumer, channelName: string = "GraphqlChannel") {
    return function (operation: Operation) {
        const subscribe = ({ next, error, complete }: { next: ForwardCallback, error: ForwardCallback, complete: ForwardCallback }) => {
            let subscribed = false;

            const subscription: Subscription = consumer.subscriptions.create(channelName, {
                connected() {
                    subscription.perform("execute", { query: operation.query, variables: operation.variables });
                    subscribed = true;
                },
                received(data: any) {
                    if (data?.result?.errors) {
                        error(data.errors);
                    }
                    if (data?.result?.data) {
                        next(data.result);
                    }
                    if (!data.more && subscribed) {
                        complete();
                    }
                }
            } as any);

            const unsubscribe = () => {
                if (subscribed) {
                    subscribed = false;
                    subscription?.unsubscribe();
                }
            };

            return { unsubscribe };
        };

        return { subscribe };
    };
}

const forwardToActionCable = createUrqlActionCableSubscription(actionCable);


const client = createClient({
    url: '/graphql',
    exchanges: [
        cacheExchange,
        fetchExchange,
        subscriptionExchange({
            forwardSubscription: forwardToActionCable as any
        }),
    ],
});
```

The change that matters at large is here:
```
                    if (!data.more && subscribed) {
                        complete();
                    }
```

I'm not sure how this translates to createActionCableHandler, which is targeted in this PR, but here are my 2c.

**Pull request merged**
