### PR TITLE
[1.10] Removed dynamic definition documentation

### PR DESCRIPTION
**Pull request by abhaynikam**
Ref: https://github.com/rmosolgo/graphql-ruby/issues/2100#issuecomment-471182814

### CODE REVIEW

**Comment by abhaynikam** [comment]
@rmosolgo Please have a look after CI is passed. Thanks

**Comment by rmosolgo** [comment]
Thanks for taking care of this!

**Comment by benbonnet** [comment]
Hello; was interested in such approach; was the previous version outdated ? Or should things be done another way ?

**Comment by rmosolgo** [comment]
Hi, in 1.8+, types can be defined using classes: 

```ruby 
class Book < GraphQL::Schema::Object 
  # ... 
end 
```

So, if you want to dynamically define types, you can use plain old Ruby: 

```ruby 
book_type = Class.new(GraphQL::Schema::Object) do 
  graphql_name "Book" 
  # ... 
end 
```

**Pull request merged**
