### PR TITLE
WIP: Fixes GraphQL Upgrader: complicated inline definition

### PR DESCRIPTION
**Pull request by esjee**
Depends on https://github.com/rmosolgo/graphql-ruby/pull/1151. Let's merge that one first!

### CODE REVIEW

**Comment by Willianvdv** [comment]
@esjee should we wait for the outcome of the discussion on #1158 before fixing this?

**Comment by esjee** [comment]
No, I think that's only relevent for https://github.com/rmosolgo/graphql-ruby/pull/1156 :smile:

**Comment by Willianvdv** [comment]
@esjee ha! You're right!

**Comment by rmosolgo** [comment]
Sorry, this branch has diverged a lot from 1.8-dev, feel free to open a fresh PR if there's more to do here!

**Pull request closed without merging**
