### PR TITLE
Fix non-null connection fields to only return one non-null error

### PR DESCRIPTION
**Pull request by rmosolgo**
This puts the behavior _back_ to how it was in 1.12.10

Also, stop resolving lists when they become dead.

Fixes https://github.com/rmosolgo/graphql-ruby/issues/3504#issuecomment-908825696

### CODE REVIEW

**Comment by swalkinshaw** [comment]
:shipit: this fixes https://github.com/rmosolgo/graphql-ruby/issues/3504#issuecomment-908825696 🎉

**Comment by swalkinshaw** [comment]
@rmosolgo it still might be worthwhile asking if this is worth "fixing". We had a unit test failing that expected only 1 error, but it's not behaviour we _have_  to preserve. Though I think from the other related issues the spec was ambiguous anyway?

**Comment by rmosolgo** [comment]
I certainly _default_ to preserving previous behaviors, unless there's some reason to change it. I can't think of any reason why fields should keep running after one of them nullifies the parent -- is there one?

**Comment by swalkinshaw** [comment]
No I think this is the best behaviour 👍  it's a bit weird that execution continues, but adding those errors basically leaks that implementation detail?

**Comment by rmosolgo** [comment]
> execution continues

I fixed that, too, here: https://github.com/rmosolgo/graphql-ruby/pull/3601/files#diff-8398a090ccfa07b5ba0482e924606c920a38f2b329ffd1d6246d29e65c9ef6a8R749

So, while lists are running, if one of them causes the result to be dead, then execution of the list stops. It's possible that objects need a similar fix 👀

**Comment by swalkinshaw** [comment]
👏  yeah confirmed that to be the case at least for the test gist we had

**Comment by rmosolgo** [comment]
I didn't think til after merging to run a quick benchmark, fixed up some memory usage in 088ecc71e

Interestinly, `be rake bench:profile_large_result` still shows 40 more bytes of memory after that change, but I can't figure out _where_ when I read the profile 😆 🤷

**Pull request merged**
