### PR TITLE
Permit valueless definitions

### PR DESCRIPTION
**Pull request by gjtorikian**
I'd like to not necessarily require values when adding my own metadata definitions.

For example, the comment in this file shows

``` ruby
# Use it in a definition
subaru_baja = Car.define do
 # ...
 all_wheel_drive true
end
```

Wouldn't it be much nicer like this? 😀 

``` ruby
# Use it in a definition
subaru_baja = Car.define do
 # ...
 has_all_wheel_drive
end
```

### CODE REVIEW

**Comment by rmosolgo** [comment]
:+1: would merge with a test, feel free to update the existing one according to your example!

**Comment by gjtorikian** [comment]
🎉

**Comment by gjtorikian** [comment]
Bump for eyes~ 😅

**Comment by rmosolgo** [comment]
Thanks for the bump, somehow I missed that followup commit!

**Pull request merged**
